// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using webAPI.data;

#nullable disable

namespace webAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220501170301_AddAnotherMigrationLOL")]
    partial class AddAnotherMigrationLOL
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("webAPI.Models.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("creatorId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("dateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("postId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("creatorId");

                    b.HasIndex("postId");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            body = "i also like pengins",
                            creatorId = 2,
                            dateCreated = new DateTime(2022, 5, 1, 17, 3, 1, 161, DateTimeKind.Utc).AddTicks(2544),
                            postId = 1
                        });
                });

            modelBuilder.Entity("webAPI.Models.Friendship", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("accepted")
                        .HasColumnType("boolean");

                    b.Property<int>("receiverId")
                        .HasColumnType("integer");

                    b.Property<int>("senderId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("receiverId");

                    b.HasIndex("senderId");

                    b.ToTable("Friendships");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            accepted = false,
                            receiverId = 2,
                            senderId = 1
                        },
                        new
                        {
                            Id = 2,
                            accepted = true,
                            receiverId = 4,
                            senderId = 3
                        });
                });

            modelBuilder.Entity("webAPI.Models.Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("avatar")
                        .HasColumnType("text");

                    b.Property<DateOnly>("dateCreated")
                        .HasColumnType("date");

                    b.Property<string>("description")
                        .HasColumnType("text");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ownerId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ownerId");

                    b.ToTable("Groups");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            avatar = "https://i.ibb.co/C61C35f/Screenshot-2022-04-24-at-20-49-25.png",
                            dateCreated = new DateOnly(1947, 11, 3),
                            description = "Chess group for nerds",
                            name = "Nicol's Chess Club",
                            ownerId = 1
                        },
                        new
                        {
                            Id = 2,
                            avatar = "https://i.ibb.co/TLCthzM/Screenshot-2022-04-24-at-20-52-57.png",
                            dateCreated = new DateOnly(1969, 11, 3),
                            description = "Hit ball with stick",
                            name = "Maties Hockey",
                            ownerId = 4
                        });
                });

            modelBuilder.Entity("webAPI.Models.Membership", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool?>("admin")
                        .HasColumnType("boolean");

                    b.Property<int?>("groupId")
                        .HasColumnType("integer");

                    b.Property<int>("userId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("groupId");

                    b.HasIndex("userId");

                    b.ToTable("Memberships");

                    b.HasData(
                        new
                        {
                            Id = 4,
                            userId = 1
                        },
                        new
                        {
                            Id = 5,
                            userId = 2
                        },
                        new
                        {
                            Id = 6,
                            userId = 3
                        },
                        new
                        {
                            Id = 7,
                            userId = 4
                        },
                        new
                        {
                            Id = 1,
                            admin = true,
                            groupId = 1,
                            userId = 1
                        },
                        new
                        {
                            Id = 9,
                            admin = false,
                            groupId = 2,
                            userId = 1
                        },
                        new
                        {
                            Id = 2,
                            admin = true,
                            groupId = 2,
                            userId = 4
                        },
                        new
                        {
                            Id = 3,
                            admin = true,
                            groupId = 1,
                            userId = 2
                        },
                        new
                        {
                            Id = 8,
                            userId = 5
                        });
                });

            modelBuilder.Entity("webAPI.Models.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("creatorId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("dateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("latitude")
                        .HasColumnType("double precision");

                    b.Property<double>("longitude")
                        .HasColumnType("double precision");

                    b.Property<bool>("video")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("creatorId");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            body = "I like penguins",
                            creatorId = 4,
                            dateCreated = new DateTime(2022, 5, 1, 17, 3, 1, 161, DateTimeKind.Utc).AddTicks(2525),
                            latitude = 29.653700000000001,
                            longitude = 79.948599999999999,
                            video = false
                        },
                        new
                        {
                            Id = 2,
                            body = "u4vuh4i7wb9atdvj11rs",
                            creatorId = 1,
                            dateCreated = new DateTime(2022, 5, 1, 17, 3, 1, 161, DateTimeKind.Utc).AddTicks(2526),
                            latitude = 82.862799999999993,
                            longitude = 135.0,
                            video = true
                        });
                });

            modelBuilder.Entity("webAPI.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("DOB")
                        .HasColumnType("date");

                    b.Property<string>("avatar")
                        .HasColumnType("text");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("firstName")
                        .HasColumnType("text");

                    b.Property<string>("lastName")
                        .HasColumnType("text");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("email")
                        .IsUnique();

                    b.HasIndex("username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DOB = new DateOnly(1943, 11, 23),
                            avatar = "https://i.ibb.co/hm99dG4/20d9de001ebe.png",
                            email = "nicolvisser@yahoo.com",
                            firstName = "Nicol",
                            lastName = "Visser",
                            password = "$2a$11$bsfmSEx8GGIK1z3yfwVA2ujra0pA5ANhppcoSnQkLaPjbjkqtxt5y",
                            username = "VisserMan"
                        },
                        new
                        {
                            Id = 2,
                            DOB = new DateOnly(2000, 6, 3),
                            avatar = "https://i.ibb.co/SBLGDZW/jc.png",
                            email = "jcmouton@protonmail.com",
                            firstName = "Jacques",
                            lastName = "Mouton",
                            password = "$2a$11$or5c8.om95LVLLBYnG3EBuEeWtcxYBFB1gmVUvvODjKzXnC/y.SJa",
                            username = "JaySea"
                        },
                        new
                        {
                            Id = 3,
                            DOB = new DateOnly(2000, 11, 23),
                            avatar = "https://i.ibb.co/jg3970L/76cb8121601e.png",
                            email = "philler@gmail.com",
                            firstName = "Philip",
                            lastName = "Schommarz",
                            password = "$2a$11$42qr0rKIaih2NgrC2aaq1eLOscArE4NzTj/HbXYmDMpBb2Wy6Ulvu",
                            username = "Fillet"
                        },
                        new
                        {
                            Id = 4,
                            DOB = new DateOnly(2000, 3, 11),
                            avatar = "https://i.ibb.co/VYbZ60Q/38816802529d.jpg",
                            email = "mssteyn@rocketmail.com",
                            firstName = "Lize",
                            lastName = "Steyn",
                            password = "$2a$11$0i8e22VuPj1H.qsqC2kzc.18KhdE0N9JgUcGzYlZiaFSopX.3wkpe",
                            username = "MorneSteyn"
                        },
                        new
                        {
                            Id = 5,
                            DOB = new DateOnly(2000, 1, 3),
                            avatar = "https://i.ibb.co/3cfRt6n/Image.png",
                            email = "eduanuys@gmail.com",
                            firstName = "Eduan",
                            lastName = "Uys",
                            password = "$2a$11$hKYNcxYJY50./ynzC2oWl.OLoir.7DeQrXOs0gZCke.T438Sczgjq",
                            username = "uysbeer"
                        });
                });

            modelBuilder.Entity("webAPI.Models.Comment", b =>
                {
                    b.HasOne("webAPI.Models.Membership", "creator")
                        .WithMany("comments")
                        .HasForeignKey("creatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("webAPI.Models.Post", "post")
                        .WithMany("comments")
                        .HasForeignKey("postId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("creator");

                    b.Navigation("post");
                });

            modelBuilder.Entity("webAPI.Models.Friendship", b =>
                {
                    b.HasOne("webAPI.Models.User", "receiver")
                        .WithMany()
                        .HasForeignKey("receiverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("webAPI.Models.User", "sender")
                        .WithMany()
                        .HasForeignKey("senderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("receiver");

                    b.Navigation("sender");
                });

            modelBuilder.Entity("webAPI.Models.Group", b =>
                {
                    b.HasOne("webAPI.Models.User", "owner")
                        .WithMany("OwnedGroups")
                        .HasForeignKey("ownerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("owner");
                });

            modelBuilder.Entity("webAPI.Models.Membership", b =>
                {
                    b.HasOne("webAPI.Models.Group", "group")
                        .WithMany("memberships")
                        .HasForeignKey("groupId");

                    b.HasOne("webAPI.Models.User", "user")
                        .WithMany("memberships")
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("group");

                    b.Navigation("user");
                });

            modelBuilder.Entity("webAPI.Models.Post", b =>
                {
                    b.HasOne("webAPI.Models.Membership", "creator")
                        .WithMany("posts")
                        .HasForeignKey("creatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("creator");
                });

            modelBuilder.Entity("webAPI.Models.Group", b =>
                {
                    b.Navigation("memberships");
                });

            modelBuilder.Entity("webAPI.Models.Membership", b =>
                {
                    b.Navigation("comments");

                    b.Navigation("posts");
                });

            modelBuilder.Entity("webAPI.Models.Post", b =>
                {
                    b.Navigation("comments");
                });

            modelBuilder.Entity("webAPI.Models.User", b =>
                {
                    b.Navigation("OwnedGroups");

                    b.Navigation("memberships");
                });
#pragma warning restore 612, 618
        }
    }
}
